name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  # CI Job for PR validation and tests
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Linting
      - name: Lint Code
        run: npm run lint

      # Run Tests (unit, integration)
      - name: Run Tests
        run: npm test

  # Job for deployment (to staging and production)
  deploy:
    needs: build-and-test  # This ensures deployment only happens if tests pass
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy to the Staging Environment (on push to dev)
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Deploying to Staging environment..."
          # Add deployment commands here (e.g., AWS ECS, Docker, Kubernetes, etc.)
          # Example for AWS ECS:
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment

      # Deploy to Production (on push to main or prod)
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod'
        run: |
          echo "Deploying to Production environment..."
          # Add production deployment commands here
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment

  # Post-deployment smoke tests
  post-deployment-tests:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Smoke Tests
        run: |
          echo "Running post-deployment smoke tests..."
          # Add smoke test commands
          npm run test:smoke

      - name: Notify team
        run: |
          echo "Deployment completed, sending notifications..."
          # Send notifications to Slack, Email, or other channels
